// The M3 color scheme behind src/styles/color-tokens.css: every role as a
// --md-sys-color-* custom property, light on :root and dark on .dark.
// Regenerate with `yarn tokens:color` after changing the seed or variant.
import { argbFromHex, hexFromArgb, Hct, MaterialDynamicColors, SchemeTonalSpot } from '@material/material-color-utilities';

export const SEED = '#1f6feb'; // current brand blue
const SPEC_VERSION = '2025';
const CONTRAST_LEVEL = 0; // M3 default

// [css name, MaterialDynamicColors key]
export const ROLES = [
  ...['primary', 'secondary', 'tertiary'].flatMap(c => {
    const C = c[0].toUpperCase() + c.slice(1);
    return [
      [c, c], [`on-${c}`, `on${C}`], [`${c}-container`, `${c}Container`], [`on-${c}-container`, `on${C}Container`],
      [`${c}-fixed`, `${c}Fixed`], [`${c}-fixed-dim`, `${c}FixedDim`],
      [`on-${c}-fixed`, `on${C}Fixed`], [`on-${c}-fixed-variant`, `on${C}FixedVariant`],
    ];
  }),
  ['error', 'error'], ['on-error', 'onError'], ['error-container', 'errorContainer'], ['on-error-container', 'onErrorContainer'],
  ['background', 'background'], ['on-background', 'onBackground'],
  ['surface', 'surface'], ['surface-dim', 'surfaceDim'], ['surface-bright', 'surfaceBright'],
  ['surface-container-lowest', 'surfaceContainerLowest'], ['surface-container-low', 'surfaceContainerLow'],
  ['surface-container', 'surfaceContainer'], ['surface-container-high', 'surfaceContainerHigh'],
  ['surface-container-highest', 'surfaceContainerHighest'],
  ['on-surface', 'onSurface'], ['surface-variant', 'surfaceVariant'], ['on-surface-variant', 'onSurfaceVariant'],
  ['surface-tint', 'surfaceTint'],
  ['outline', 'outline'], ['outline-variant', 'outlineVariant'],
  ['inverse-surface', 'inverseSurface'], ['inverse-on-surface', 'inverseOnSurface'], ['inverse-primary', 'inversePrimary'],
  ['scrim', 'scrim'], ['shadow', 'shadow'],
];

export function generateScheme(isDark) {
  const scheme = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, CONTRAST_LEVEL, SPEC_VERSION);
  return Object.fromEntries(ROLES.map(([name, key]) => [name, hexFromArgb(MaterialDynamicColors[key].getArgb(scheme))]));
}

export function renderCss() {
  const block = (selector, colors) =>
    `${selector} {\n${Object.entries(colors).map(([n, v]) => `  --md-sys-color-${n}: ${v};`).join('\n')}\n}\n`;
  return (
    `/* Generated by scripts/generate-color-tokens.mjs — do not edit by hand.\n` +
    `   Seed ${SEED}, TonalSpot, spec ${SPEC_VERSION}, contrast ${CONTRAST_LEVEL}. */\n\n` +
    block(':root', generateScheme(false)) + '\n' + block('.dark', generateScheme(true)) + '\n' +
    `/* Tailwind utilities for every role: bg-primary-container, text-on-surface-variant, ... */\n` +
    `@theme inline {\n${ROLES.map(([n]) => `  --color-${n}: var(--md-sys-color-${n});`).join('\n')}\n}\n`
  );
}
