// The browser icons, from the Mezzo mark (src/assets/mezzo-mark.svg), the
// app icon's solid blue mark. Writes
//   public/favicon.svg        the mark
//   public/favicon.ico        16, 32 and 48px (for browsers without SVG
//                             icons)
//   public/apple-touch-icon.png  180px on white, like the app icon (iOS fills
//                             transparency with black)
//   public/logo192.png, logo512.png  the web app manifest's icons, on white
// Run with `yarn icons:favicon`. Renders with the installed Google Chrome,
// through Playwright.
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from '@playwright/test';

const ROOT = path.resolve(import.meta.dirname, '..');
const read = (file: string) => fs.readFileSync(path.join(ROOT, file), 'utf8');
const write = (file: string, data: string | Buffer) =>
  fs.writeFileSync(path.join(ROOT, file), data);

// The app icon's background (app/assets/AppIcon.icon/icon.json).
const BACKGROUND = '#ffffff';

const mark = read('src/assets/mezzo-mark.svg');
const markPath = mark.match(/<path id="mark" [^>]*\/>/)?.[0];
if (!markPath) throw new Error('mezzo-mark.svg has no <path id="mark">');

// Square around the mark, which mezzo-mark.svg crops to 358 150 342 714.
const svg =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="164 142 730 730">` +
  `<!-- Generated by scripts/generate-favicon.mts. -->` +
  `${markPath}</svg>\n`;
write('public/favicon.svg', svg);

const browser = await chromium.launch({ channel: 'chrome' });

/** `padding`: the share of each side left empty around the mark. */
async function renderPng(
  size: number,
  { background = 'transparent', padding = 0 } = {}
) {
  const inset = Math.round(size * padding);
  const markSize = size - 2 * inset;
  // A page per size: growing a reused page's viewport can tile stale content
  // into the screenshot.
  const page = await browser.newPage({
    colorScheme: 'light',
    viewport: { width: size, height: size },
  });
  await page.setContent(
    `<body style="margin:0;padding:${inset}px;background:${background}">` +
      `<img src="data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}" ` +
      `width="${markSize}" height="${markSize}" style="display:block"></body>`
  );
  await page.locator('img').evaluate(img => (img as HTMLImageElement).decode());
  const png = await page.screenshot({
    omitBackground: background === 'transparent',
  });
  await page.close();
  return png;
}

// An ICO holding PNGs: a 6-byte header, a 16-byte entry per image, then
// the images.
function ico(images: { size: number; png: Buffer }[]) {
  const header = Buffer.alloc(6 + 16 * images.length);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2); // icon
  header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach(({ size, png }, index) => {
    const entry = 6 + 16 * index;
    header.writeUInt8(size % 256, entry); // 256 is stored as 0
    header.writeUInt8(size % 256, entry + 1);
    header.writeUInt16LE(1, entry + 4); // color planes
    header.writeUInt16LE(32, entry + 6); // bits per pixel
    header.writeUInt32LE(png.length, entry + 8);
    header.writeUInt32LE(offset, entry + 12);
    offset += png.length;
  });
  return Buffer.concat([header, ...images.map(({ png }) => png)]);
}

const icoImages: { size: number; png: Buffer }[] = [];
for (const size of [16, 32, 48]) {
  icoImages.push({ size, png: await renderPng(size) });
}
write('public/favicon.ico', ico(icoImages));
// Padded: iOS rounds the corners off and adds no margin of its own.
write(
  'public/apple-touch-icon.png',
  await renderPng(180, { background: BACKGROUND, padding: 0.14 })
);
for (const size of [192, 512]) {
  write(
    `public/logo${size}.png`,
    await renderPng(size, { background: BACKGROUND, padding: 0.14 })
  );
}

await browser.close();
console.log(
  'Wrote public/favicon.svg, favicon.ico, apple-touch-icon.png, logo192.png and logo512.png'
);
