// The browser icons, from the Mezzo mark (src/assets/mezzo-mark.svg) in the
// M3 primary tones of src/styles/color-tokens.css: its three segments light
// to dark, top to bottom. Writes
//   public/favicon.svg        the mark, switching to the dark scheme's tones
//                             in dark mode
//   public/favicon.ico        16, 32 and 48px, light tones (for browsers
//                             without SVG icons)
//   public/apple-touch-icon.png  180px on the background color (iOS fills
//                             transparency with black)
// Run with `yarn icons:favicon` after `yarn tokens:color`. Renders with the
// installed Google Chrome, through Playwright.
import fs from 'node:fs';
import path from 'node:path';
import { chromium } from '@playwright/test';

const ROOT = path.resolve(import.meta.dirname, '..');
const read = (file: string) => fs.readFileSync(path.join(ROOT, file), 'utf8');
const write = (file: string, data: string | Buffer) =>
  fs.writeFileSync(path.join(ROOT, file), data);

/** The --md-sys-color-* values in the first `selector { ... }` block. */
function tokens(css: string, selector: string) {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`No ${selector} block in color-tokens.css`);
  const block = css.slice(start, css.indexOf('}', start));
  const values: Record<string, string> = {};
  for (const [, name, value] of block.matchAll(
    /--md-sys-color-([\w-]+):\s*(#[0-9a-f]{6})/gi
  )) {
    values[name!] = value!;
  }
  return (name: string) => {
    const value = values[name];
    if (!value) throw new Error(`No ${name} under ${selector}`);
    return value;
  };
}

const css = read('src/styles/color-tokens.css');
const light = tokens(css, ':root');
const dark = tokens(css, '.dark');

// Top, middle and bottom segments.
const LIGHT = [
  light('primary-fixed-dim'),
  light('primary'),
  light('on-primary-fixed-variant'),
];
const DARK = [
  dark('primary-fixed'),
  dark('primary'),
  dark('primary-container'),
];

const mark = read('src/assets/mezzo-mark.svg');
const match = (pattern: RegExp) => {
  const found = mark.match(pattern);
  if (!found) throw new Error(`mezzo-mark.svg has no match for ${pattern}`);
  return found;
};
const markPath = match(/<path id="mark" d="[^"]*"\/>/)[0];
const clipPaths = ['ct', 'cm', 'cb']
  .map(id => match(new RegExp(`<clipPath id="${id}">.*?</clipPath>`))[0])
  .join('');
const transform = match(/<g transform="([^"]*)">/)[1];

const fills = ([top, middle, bottom]: string[]) =>
  `.t{fill:${top}}.m{fill:${middle}}.b{fill:${bottom}}`;

// Square around the mark, which mezzo-mark.svg crops to 366 178 322 656.
const svg =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="177 156 700 700">` +
  `<!-- Generated by scripts/generate-favicon.mts. -->` +
  `<style>${fills(LIGHT)}@media (prefers-color-scheme:dark){${fills(DARK)}}</style>` +
  `<defs>${markPath}${clipPaths}</defs>` +
  `<g transform="${transform}">` +
  `<use href="#mark" clip-path="url(#ct)" class="t"/>` +
  `<use href="#mark" clip-path="url(#cm)" class="m"/>` +
  `<use href="#mark" clip-path="url(#cb)" class="b"/>` +
  `</g></svg>\n`;
write('public/favicon.svg', svg);

const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ colorScheme: 'light' });

/** `padding`: the share of each side left empty around the mark. */
async function renderPng(
  size: number,
  { background = 'transparent', padding = 0 } = {}
) {
  const inset = Math.round(size * padding);
  const markSize = size - 2 * inset;
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<body style="margin:0;padding:${inset}px;background:${background}">` +
      `<img src="data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}" ` +
      `width="${markSize}" height="${markSize}" style="display:block"></body>`
  );
  await page.locator('img').evaluate(img => (img as HTMLImageElement).decode());
  return page.screenshot({ omitBackground: background === 'transparent' });
}

// An ICO holding PNGs: a 6-byte header, a 16-byte entry per image, then
// the images.
function ico(images: { size: number; png: Buffer }[]) {
  const header = Buffer.alloc(6 + 16 * images.length);
  header.writeUInt16LE(0, 0);
  header.writeUInt16LE(1, 2); // icon
  header.writeUInt16LE(images.length, 4);
  let offset = header.length;
  images.forEach(({ size, png }, index) => {
    const entry = 6 + 16 * index;
    header.writeUInt8(size % 256, entry); // 256 is stored as 0
    header.writeUInt8(size % 256, entry + 1);
    header.writeUInt16LE(1, entry + 4); // color planes
    header.writeUInt16LE(32, entry + 6); // bits per pixel
    header.writeUInt32LE(png.length, entry + 8);
    header.writeUInt32LE(offset, entry + 12);
    offset += png.length;
  });
  return Buffer.concat([header, ...images.map(({ png }) => png)]);
}

const icoImages: { size: number; png: Buffer }[] = [];
for (const size of [16, 32, 48]) {
  icoImages.push({ size, png: await renderPng(size) });
}
write('public/favicon.ico', ico(icoImages));
write(
  'public/apple-touch-icon.png',
  // Padded: iOS rounds the corners off and adds no margin of its own.
  await renderPng(180, { background: light('background'), padding: 0.14 })
);

await browser.close();
console.log('Wrote public/favicon.svg, favicon.ico and apple-touch-icon.png');
