// The M3 type scale behind src/styles/type-tokens.css. Values (px) are from
// androidx TypeScaleTokens.kt; tracking is in px (sp). Regenerate with
// `yarn tokens:type`.

export const TYPEFACE = "'Roboto Flex', Roboto, system-ui, sans-serif";

// [role, size, fontSize, lineHeight, tracking, weight]
export const SCALE: ReadonlyArray<
  readonly [string, string, number, number, number, number]
> = [
  ['display', 'large', 57, 64, -0.25, 400],
  ['display', 'medium', 45, 52, 0, 400],
  ['display', 'small', 36, 44, 0, 400],
  ['headline', 'large', 32, 40, 0, 400],
  ['headline', 'medium', 28, 36, 0, 400],
  ['headline', 'small', 24, 32, 0, 400],
  ['title', 'large', 22, 28, 0, 400],
  ['title', 'medium', 16, 24, 0.15, 500],
  ['title', 'small', 14, 20, 0.1, 500],
  ['body', 'large', 16, 24, 0.5, 400],
  ['body', 'medium', 14, 20, 0.25, 400],
  ['body', 'small', 12, 16, 0.4, 400],
  ['label', 'large', 14, 20, 0.1, 500],
  ['label', 'medium', 12, 16, 0.5, 500],
  ['label', 'small', 11, 16, 0.5, 500],
];

// Emphasized styles are one step heavier: regular (400) -> medium (500),
// medium (500) -> bold (700).
export const emphasize = (weight: number): number =>
  weight === 400 ? 500 : 700;

const rem = (px: number) => `${+(px / 16).toFixed(4)}rem`;

export function styles(): {
  name: string;
  fontSize: number;
  lineHeight: number;
  tracking: number;
  weight: number;
}[] {
  return SCALE.flatMap(
    ([role, size, fontSize, lineHeight, tracking, weight]) => {
      const base = {
        name: `${role}-${size}`,
        fontSize,
        lineHeight,
        tracking,
        weight,
      };
      return [
        base,
        { ...base, name: `${base.name}-emphasized`, weight: emphasize(weight) },
      ];
    }
  );
}

export function renderCss(): string {
  const vars = styles()
    .map(({ name, fontSize, lineHeight, tracking, weight }) =>
      [
        `  --md-sys-typescale-${name}-font: var(--md-ref-typeface-plain);`,
        `  --md-sys-typescale-${name}-weight: ${weight};`,
        `  --md-sys-typescale-${name}-size: ${rem(fontSize)};`,
        `  --md-sys-typescale-${name}-line-height: ${rem(lineHeight)};`,
        `  --md-sys-typescale-${name}-tracking: ${tracking === 0 ? '0' : `${tracking}px`};`,
      ].join('\n')
    )
    .join('\n');
  const theme = styles()
    .map(({ name }) =>
      [
        `  --text-${name}: var(--md-sys-typescale-${name}-size);`,
        `  --text-${name}--line-height: var(--md-sys-typescale-${name}-line-height);`,
        `  --text-${name}--letter-spacing: var(--md-sys-typescale-${name}-tracking);`,
        `  --text-${name}--font-weight: var(--md-sys-typescale-${name}-weight);`,
      ].join('\n')
    )
    .join('\n');
  return (
    `/* Generated by scripts/generate-type-tokens.mts — do not edit by hand. */\n\n` +
    `:root {\n  --md-ref-typeface-brand: ${TYPEFACE};\n  --md-ref-typeface-plain: ${TYPEFACE};\n\n${vars}\n}\n\n` +
    `/* Tailwind: text-headline-large, text-title-medium-emphasized, ... set size,\n` +
    `   line height, tracking and weight together. font-brand / font-plain set the family. */\n` +
    `@theme inline {\n  --font-brand: var(--md-ref-typeface-brand);\n  --font-plain: var(--md-ref-typeface-plain);\n\n${theme}\n}\n`
  );
}
